### ISSUE TITLE
Notebook clip_fine_tuning - not correct usage `device` 

### ISSUE THREAD

**Issue by ayasyrev** [iterative/datachain-examples#6]
### Description

Notebook: datachain/examples/multimodal/clip_fine_tuning.ipynb
If gpu available, we choose "cuda" `device = "cuda" if torch.cuda.is_available() else "cpu"`
Next we move model to `device` but don't move image and text.

`clip_similarity_scores` also don't care about `device`.
So we need move model back to cpu or add this functionality to this function.
We can add `device` argument to function or check model device inside function.

Ready to prepare PR with fix in notebook and code.

### Version Info

```Text
0.3.1
Python 3.12.4
```

**Comment by dberenbaum** [comment]
@ayasyrev Do you still plan to prepare a fix in the code and example?

**Comment by ayasyrev** [comment]
Sorry for long pause. Yes, I still plan fix it, hope to do it several days.

**Comment by dberenbaum** [comment]
Thanks, @ayasyrev! Please let us know if we can help or you have questions.
